version: "3.0"
services:
  job_board_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_board
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
